### PR TITLE
Add default value for fe user group for special price and quantity discount

### PR DESCRIPTION
**Pull request by paul-keller**
Has to be fixed in branch 3.x as well

### CODE REVIEW

**Review by t3pwa — COMMENTED** [review]
related: https://github.com/extcode/cart_products/issues/114

**Comment by rintisch** [comment]
Quite late but: @paul-keller Why is this PR necessary? :)

**Comment by paul-keller** [comment]
Sorry. To long ago.
I believe that it was not possible to set a quantity discount for all groups in the backend because the default value of frontend_user_group was not set.

**Comment by rintisch** [comment]
Thanks for the answer!

According to the docs is this still relevant: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Select/Single/Index.html#confval-select-single-items

I do not have this error but might depend on the setup. I think this cannot harm. @extcode What do you think?

**Comment by extcode** [comment]
I'll have a look at this due to the next days.

**Review by extcode — APPROVED** [review]

**Comment by rintisch** [comment]
Close as merged with [57a6fdb](https://github.com/extcode/cart_products/commit/57a6fdbd39b80a7319d146fdb83987ee1f1dc261)

**Pull request merged**
